# Configuration for parallelized PlotManager plots
---
.base_parallel_plots: !pspace
  # creator: pyplot  (default)

  module: .basic
  plot_func: lineplot

  # Define some large-enough sweep
  x: vectors/times
  y: !sweep
    default: vectors/values
    values:
      - vectors/values
      - vectors/more_values
      - vectors/even_more_values

  fmt: !sweep
    default: go-
    values:
      - go-
      - r+
      - or
      - "--"

  linewidth: !sweep
    default: 1
    linspace: [1, 11, 6]


# .............................................................................

process: !pspace
  based_on:
    - .base_parallel_plots

  parallel:
    enabled: true
    executor: process


thread: !pspace
  based_on:
    - .base_parallel_plots

  parallel:
    enabled: true
    executor: thread  # working, but slower than sequential


single_process_fallback: !pspace
  based_on:
    - .base_parallel_plots

  parallel:
    enabled: true
    executor: process
    max_workers: 1


rel_max_workers_definition: !pspace
  based_on:
    - .base_parallel_plots

  parallel:
    enabled: true
    executor: process
    max_workers: -1  # deduce from os.cpu_count()


fallback_no_fail: !pspace
  based_on:
    - .base_parallel_plots

  parallel:
    enabled: true
    executor: process
    fallback_on_fail: true


benchmark_overhead: !pspace
  based_on:
    - .base_parallel_plots

  parallel:
    enabled: true
    executor: process
    benchmark_overhead: 10


# .. Check exceptions .........................................................
# These are set `enabled: false`, because they need to be run explicitly

error_bad_executor_name: !pspace
  enabled: false
  based_on:
    - .base_parallel_plots

  parallel:
    enabled: true
    executor: some_bad_eXeCuTor_name


error_propagates_from_thread: !pspace
  enabled: false
  based_on:
    - .base_parallel_plots

  some_bad_argument: this should cause an exception

  parallel:
    enabled: true
    executor: thread


error_propagates_from_process: !pspace
  enabled: false
  based_on:
    - .base_parallel_plots

  another_bad_argument: this should cause an exception

  parallel:
    enabled: true
    executor: process



fallback_with_fail: !pspace
  enabled: false
  based_on:
    - .base_parallel_plots

  some_bad_argument: should cause exception

  parallel:
    enabled: true
    executor: process
    fallback_on_fail: false


without_exception_summary: !pspace
  enabled: false
  based_on:
    - .base_parallel_plots

  some_bad_argument: should cause exception

  parallel:
    enabled: true
    executor: process
    fallback_on_fail: false
    show_exception_summary: false
